# Generated by Django 3.0.2 on 2021-08-06 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='schedule',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.CharField(blank=True, choices=[('1', '9:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '13:00'), ('6', '14:00'), ('7', '15:00'), ('8', '16:00'), ('9', '17:00'), ('10', '18:00'), ('11', '19:00'), ('12', '20:00'), ('13', '21:00'), ('14', '22:00'), ('15', '23:00'), ('16', '24:00')], max_length=255, null=True, verbose_name='終了'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, choices=[('1', '9:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '13:00'), ('6', '14:00'), ('7', '15:00'), ('8', '16:00'), ('9', '17:00'), ('10', '18:00'), ('11', '19:00'), ('12', '20:00'), ('13', '21:00'), ('14', '22:00'), ('15', '23:00'), ('16', '24:00')], max_length=255, null=True, verbose_name='開始'),
        ),
        migrations.DeleteModel(
            name='End',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Start',
        ),
    ]
