# Generated by Django 2.2.5 on 2021-08-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'アカウント', 'verbose_name_plural': 'アカウント'},
        ),
    ]
