# Generated by Django 3.0.2 on 2021-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='開始'),
        ),
    ]
