# Generated by Django 3.0.2 on 2021-08-06 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210806_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Date', verbose_name='日付'),
        ),
    ]
