# Generated by Django 3.0.2 on 2021-08-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='full_name',
        ),
    ]
