# Generated by Django 3.0.2 on 2021-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210806_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(unique=True, verbose_name='日付'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
