# Generated by Django 2.2.5 on 2021-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210731_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, help_text='HTMLタグは使えません。', verbose_name='本文'),
        ),
    ]
