# Generated by Django 3.2.6 on 2021-08-30 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210821_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, verbose_name='勤務時間')),
                ('time_range', models.CharField(max_length=255, verbose_name='勤務期間')),
                ('date', models.DateField(verbose_name='日付')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_shift', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
