# Generated by Django 3.0.2 on 2021-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210807_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Post', verbose_name='シフト'),
        ),
    ]
