# Generated by Django 3.0.2 on 2021-08-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210805_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
