# Generated by Django 3.2.6 on 2021-08-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '希望シフト', 'verbose_name_plural': '希望シフト'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': '完成シフト', 'verbose_name_plural': '完成シフト'},
        ),
    ]
