# Generated by Django 3.0.2 on 2021-08-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210807_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='開始'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Post', verbose_name='シフト'),
        ),
    ]
