# Generated by Django 3.0.2 on 2021-08-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210807_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.CharField(blank=True, choices=[('1', '9:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '13:00'), ('6', '14:00'), ('7', '15:00'), ('8', '16:00'), ('9', '17:00'), ('10', '18:00'), ('11', '19:00'), ('12', '20:00'), ('13', '21:00'), ('14', '22:00'), ('15', '23:00'), ('16', '24:00')], max_length=255, null=True, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, choices=[('1', '9:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '13:00'), ('6', '14:00'), ('7', '15:00'), ('8', '16:00'), ('9', '17:00'), ('10', '18:00'), ('11', '19:00'), ('12', '20:00'), ('13', '21:00'), ('14', '22:00'), ('15', '23:00'), ('16', '24:00')], max_length=255, null=True, verbose_name='開始'),
        ),
    ]
