# Generated by Django 3.2.6 on 2021-09-29 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210929_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='休憩時間'),
        ),
    ]
