# Generated by Django 3.0.2 on 2021-08-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210807_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post', verbose_name='シフト'),
        ),
    ]
